[package]
name = "claudectl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
owo-colors = { version = "4.0", features = ["supports-colors"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
