avoid-breaking-exported-api = false
msrv = "1.76.0"
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 7
type-complexity-threshold = 250
trivial-copy-size-limit = 128
pass-by-value-size-limit = 256
semicolon-inside-block-ignore-singleline = false
semicolon-outside-block-ignore-multiline = false
doc-valid-idents = ["ClaudeCtl", "claudectl", "worktrees", "worktree"]
too-many-lines-threshold = 100
array-size-threshold = 512000
vec-box-size-threshold = 4096
max-trait-bounds = 3
max-struct-bools = 3
max-fn-params-bools = 3
warn-on-all-wildcard-imports = false
disallowed-names = ["foo", "baz", "quux"]
suppress-restriction-lint-in-const = false