edition = "2021"
max_width = 100
tab_spaces = 4
use_small_heuristics = "Default"
match_block_trailing_comma = false
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true