name: CLI Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cli-test:
    name: CLI Integration Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test CLI installation
        run: |
          npm pack
          npm install -g ./claudectl-*.tgz

      - name: Test CLI commands
        run: |
          claudectl --version
          claudectl --help

      - name: Setup test git repository (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir test-repo
          cd test-repo
          git init
          git config user.email "test@example.com"
          git config user.name "Test User"
          echo "# Test Repo" > README.md
          git add README.md
          git commit -m "Initial commit"

      - name: Setup test git repository (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir test-repo
          cd test-repo
          git init
          git config user.email "test@example.com"
          git config user.name "Test User"
          echo "# Test Repo" > README.md
          git add README.md
          git commit -m "Initial commit"

      - name: Test claudectl init (Unix)
        if: runner.os != 'Windows'
        run: |
          cd test-repo
          claudectl init test-project
          ls -la

      - name: Test claudectl init (Windows)
        if: runner.os == 'Windows'
        run: |
          cd test-repo
          claudectl init test-project
          dir

      - name: Cleanup
        run: npm uninstall -g claudectl